todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo_app.urls'))
]

todo_app/urls.py
from django.urls import path

from . import views

app_name = 'todo_app'

urlpatterns = [
	path('', views.index, name='index'),
	path('add_task/', views.add_task, name='add_task'),
	path('mark_task_complete/', views.mark_task_complete, name='mark_task_complete'),
	path('unmark_task_complete/', views.unmark_task_complete, name='unmark_task_complete'), 
	path('delete_task/', views.delete_task, name='delete_task'),
	path('update_task/', views.update_task, name='update_task')
]

todo_app/models.py
from django.db import models

# Create your models here.

class Todos(models.Model):
	task = models.CharField(max_length=1000)
	completed = models.BooleanField(default=False)
	def __str__(self):
		return self.task

todo_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404	
from .models import Todos
from django.template import loader
from django.shortcuts import render
from django.urls import reverse
# Create your views here.

def index(request):
	task_list = Todos.objects.all()
	output = ', '.join([q.task for q in task_list])
	context = {
		'task_list': task_list
	}
	return render(request, 'todo_app/index.html', context)

def add_task(request):
	new_task = request.GET.get('input_task')
	todo = Todos(task=new_task)
	todo.save()
	return HttpResponseRedirect(reverse('todo_app:index'))

def mark_task_complete(request):
	id = request.GET.get('id')
	try:
		todo = Todos.objects.get(pk=id)
	except Todos.DoesNotExist:
		raise Http404("Todo does not exist")
	todo.completed = True
	todo.save()
	return HttpResponseRedirect(reverse('todo_app:index'))

def unmark_task_complete(request):
	id = request.GET.get('id')
	try:
		todo = Todos.objects.get(pk=id)
	except Todos.DoesNotExist:
		raise Http404("Todo does not exist")
	todo.completed = False
	todo.save()
	return HttpResponseRedirect(reverse('todo_app:index'))

def delete_task(request):
	id = request.GET.get('id')
	try:
		todo = Todos.objects.get(pk=id)
	except Todos.DoesNotExist:
		raise Http404("Todo does not exist")
	todo.delete()
	return HttpResponseRedirect(reverse('todo_app:index'))

def update_task(request):
	id = request.GET.get('id')
	updated_task = request.GET.get('updated_task')
	try:
		todo = Todos.objects.get(pk=id)
	except Todos.DoesNotExist:
		raise Http404("Todo does not exist")
	todo.task = updated_task
	todo.save()
	return HttpResponseRedirect(reverse('todo_app:index'))
	

todo_app/templates/todo_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - To-do list in pure JavaScript</title>
  <link rel="stylesheet" href="{% static "todo_app/style.css" %}">

</head>
<body>
  
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="container flex lists">
  <div class="one_list">
    <div class="header_title">
      <span class="input_title">Your to do list</span>
      <button type="button" class="edit_title_button"><i class="fa fa-pencil" aria-hidden="true"></i></button>
    </div>
    <form action="{% url 'todo_app:add_task' %}" method='get' >
      <input type="text" id="input_task" name="input_task" placeholder="New task"></input>
      <button type="submit" value="submit" id="add_button"><i class="fa fa-plus" aria-hidden="true"></i></button>
    
    <div>
      <ul id="task_list">
         {% for task in task_list %}
           {% if not task.completed %}
            <li>
              <input type="checkbox" class="checkbox" name="undone" value={{task.id}} data-catid="{{task.id}}"
              ></input>
              <span class="input">{{task.task}}</span>
              <button type="button" class="edit_task_button" id="{{task.id}}"><i class="fa fa-pencil" aria-hidden="true"></i></button>
              <button type="button" class="delete" data-catid='{{task.id}}'><i class="fa fa-trash-o" aria-hidden="true"></i></button>
            </li>
            {% endif %}
        {% endfor %}

      </ul>	
      <h2 id="completed_title">Completed</h2>
      <ul id="completed_list">
        {% for task in task_list %}
          {% if task.completed %}
            <li class='complete'>
              <input type="checkbox" class="checkbox" name='done' checked value={{task.id}} data-catid='{{task.id}}'></input>
              <span class="input" >{{task.task}}</span>
              <button type="button" class="delete" data-catid='{{task.id}}'><i class="fa fa-trash-o" aria-hidden="true"></i></button>
            </li>
          {% endif %}
        {% endfor %}
      </ul>				
    </div>
    </form>
  </div>
  <ul>
   
  </ul>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script type="text/javascript" src="{% static "todo_app/script.js" %}"></script>
</body>
</html>